root = "."
tmp_dir = "/tmp"

[build]
  bin = "./dist/server"
  cmd = "go build -o ./dist/server cmd/main.go"
  delay = 100
  exclude_dir = ["web/node_modules"]
  exclude_file = []
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "css"]
  kill_delay = "500ms"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
